name: web-check
services:
  web-check:
    image: lissy93/web-check:latest
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped
    ports:
      - 13000:3000
    x-casaos:
      ports:
        - container: "13000"
          description:
            en_us: Web-Check Web UI Port 
            zh_cn: Web-Check ç®¡ç†é¡µé¢ç«¯å£
    container_name: web-check
x-casaos:
  architectures:
    - amd64
  author: arch3rPro
  category: Pentest
  description:
    en_us: ğŸ•µï¸â€â™‚ï¸ All-in-one OSINT tool for analysing any website.
    zh_cn: ä¸€æ¬¾è¶…é…·ã€åŠŸèƒ½å¼ºå¤§çš„ä¸€ä½“åŒ–ç½‘ç«™æµ‹è¯•å·¥å…·ã€‚
  developer: Lissy93
  icon: https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Web-Check/Web-Check.png  
  screenshot_link:
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Web-Check/screenshot-1.png
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Web-Check/screenshot-2.png
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Web-Check/screenshot-3.png
    - https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Web-Check/screenshot-4.png
  tagline:
    en_us: All-in-one OSINT tool
    zh_cn: ä¸€ä½“åŒ–OSINTå·¥å…·
  thumbnail: https://raw.githubusercontent.com/arch3rPro/Pentest-Docker/master/Apps/Web-Check/thumbnail.png
  index: /
  scheme: http
  tips:
    custom: |-
      è¯·åˆæ³•ä½¿ç”¨å·¥å…·ï¼Œåˆ‡å¿Œæœªæˆæƒæ¸—é€ï¼ï¼
  title:
    custom: Web-Check
  port_map: "13000"
